export const REASONS_YOU_ARE_AMAZING = [
  'Your Smile',
  'Your Kindness',
  'Your Eyes',
  'Your Personality',
  'Your Positivity',
  'Your Heart',
  'Your Strength',
  'Your Dreams',
  'Your Innocence',
  'Your Happiness',
  'Your Laugh',
  'Your Warmth',
  'Your Grace',
  'Your Spirit',
  'Your Compassion',
  'Your Intelligence',
  'Your Creativity',
  'Your Determination',
  'Your Gentleness',
  'Your Courage',
  'Your Honesty',
  'Your Generosity',
  'Your Patience',
  'Your Wisdom',
  'Your Humor',
  'Your Energy',
  'Your Passion',
  'Your Authenticity',
  'Your Resilience',
  'Your Empathy',
  'Your Charm',
  'Your Elegance',
  'Your Joy',
  'Your Light',
  'Your Magic',
  'Your Voice',
  'Your Presence',
  'Your Aura',
  'Your Soul',
  'Your Radiance',
  'Your Sparkle',
  'Your Glow',
  'Your Beauty',
  'Your Sweetness',
  'Your Caring Nature',
  'Your Thoughtfulness',
  'Your Optimism',
  'Your Sincerity',
  'Your Uniqueness',
  'Your Brilliance',
  'Your Tenderness',
  'Your Confidence',
  'Your Humility',
  'Your Adventurous Spirit',
  'Your Calmness',
  'Your Enthusiasm',
  'Your Loyalty',
  'Your Trustworthiness',
  'Your Supportiveness',
  'Your Encouragement',
  'Your Understanding',
  'Your Forgiveness',
  'Your Open Heart',
  'Your Beautiful Mind',
  'Your Inspiring Nature',
  'Your Inner Peace',
  'Your Outer Glow',
  'Your Playfulness',
  'Your Maturity',
  'Your Sensitivity',
  'Your Boldness',
  'Your Softness',
  'Your Fire',
  'Your Calm Waters',
  'Your Starlight',
  'Your Moonbeam',
  'Your Sunshine',
  'Your Rainbow',
  'Your Flower Garden',
  'Your Butterfly Wings',
  'Your Ocean Depth',
  'Your Mountain Strength',
  'Your Sky Dreams',
  'Your Cloud Whispers',
  'Your Raindrop Kisses',
  'Your Snowflake Touch',
  'Your Autumn Warmth',
  'Your Spring Bloom',
  'Your Summer Joy',
  'Your Winter Coziness',
  'Your Melody',
  'Your Harmony',
  'Your Rhythm',
  'Your Poetry',
  'Your Art',
  'Your Story',
  'Your Chapter',
  'Your Beginning',
  'Your Journey',
  'Your Destination',
  'Your Everything',
];

export const BIRTHDAY_WISHES = [
  'May your birthday be as beautiful as your smile.',
  'Wishing you a day filled with love and laughter.',
  'May all your dreams take flight today.',
  'You deserve all the happiness in the world.',
  'May this year bring you endless joy.',
  'Your presence makes the world a brighter place.',
  'May your heart be filled with warmth today.',
  'Wishing you magical moments and sweet memories.',
  'May your special day sparkle with wonder.',
  'You are a gift to everyone who knows you.',
  'May your birthday bloom with beautiful surprises.',
  'Wishing you sunshine, smiles, and sweet treats.',
  'May your year ahead be your best one yet.',
  'You light up every room you enter.',
  'May today be as extraordinary as you are.',
  'Wishing you love that grows stronger each day.',
  'May your birthday be wrapped in golden moments.',
  'You make ordinary days feel magical.',
  'May your wishes come true, one by one.',
  'Wishing you peace, love, and endless happiness.',
  'May your heart dance with joy today.',
  'You deserve a celebration as wonderful as you.',
  'May stars align to bless your special day.',
  'Wishing you laughter that echoes through the year.',
  'May your birthday be a beautiful beginning.',
  'You are loved more than words can express.',
  'May today bring you everything your heart desires.',
  'Wishing you moments that take your breath away.',
  'May your kindness return to you tenfold.',
  'You are the reason someone smiles today.',
  'May your birthday glow with pure happiness.',
  'Wishing you adventures as beautiful as your spirit.',
  'May your dreams blossom like spring flowers.',
  'You are a masterpiece in every way.',
  'May today be filled with sweet serendipity.',
  'Wishing you a year of growth and grace.',
  'May your birthday sparkle like champagne.',
  'You bring color to a grey world.',
  'May your heart overflow with gratitude and joy.',
  'Wishing you sunsets as beautiful as your soul.',
  'May this birthday mark the start of amazing things.',
  'You are stronger than you know.',
  'May your day be sprinkled with fairy dust.',
  'Wishing you warmth, wonder, and whimsy.',
  'May your birthday be a symphony of happiness.',
  'You are the melody in life\'s beautiful song.',
  'May today remind you how special you are.',
  'Wishing you petals of joy and petals of love.',
  'May your birthday candle light up your path.',
  'You are a constellation of wonderful qualities.',
  'May your year be painted in the brightest colors.',
  'Wishing you moonlit walks and starry dreams.',
  'May your birthday be as sweet as you are.',
  'You are a rare and precious gem.',
  'May today shower you with blessings.',
  'Wishing you a garden of beautiful moments.',
  'May your heart sing with happiness today.',
  'You are the sunshine on a cloudy day.',
  'May your birthday unfold like a perfect story.',
  'Wishing you magic in every moment.',
  'May your smile never fade.',
  'You are loved beyond measure.',
  'May today be the first page of your best chapter.',
  'Wishing you butterflies and blooming flowers.',
  'May your birthday be a canvas of joy.',
  'You are the definition of beautiful.',
  'May your wishes float up to the stars.',
  'Wishing you golden hours and silver linings.',
  'May your day be as lovely as a rose garden.',
  'You make the world a kinder place.',
  'May your birthday be wrapped in stardust.',
  'Wishing you serenity and spectacular surprises.',
  'May your heart be as full as the moon tonight.',
  'You are a blessing to this world.',
  'May today bring you closer to your dreams.',
  'Wishing you a celebration fit for royalty.',
  'May your birthday shimmer with delight.',
  'You are poetry in motion.',
  'May your year ahead be luminous.',
  'Wishing you fireflies and fairy lights.',
  'May your special day be unforgettable.',
  'You are the star of today\'s show.',
  'May your birthday bloom with infinite possibilities.',
  'Wishing you warmth like a summer breeze.',
  'May your heart be light and your spirit free.',
  'You are absolutely amazing in every way.',
  'May today be the sweetest day of the year.',
  'Wishing you lanterns of hope lighting your path.',
  'May your birthday be a treasure chest of joy.',
  'You are the most wonderful person I know.',
  'May your dreams soar higher than ever before.',
  'Wishing you a day as magical as you are.',
  'May your birthday be filled with pure wonder.',
  'You deserve the universe and more.',
  'May today be a celebration of your beautiful soul.',
  'Wishing you endless reasons to smile.',
  'May your year be as radiant as your heart.',
  'You are the gift that keeps on giving.',
  'May your birthday be absolutely perfect.',
  'Wishing you love, light, and limitless joy.',
  'May all your birthday wishes come true.',
  'You make every day feel like a celebration.',
  'May your special day be as extraordinary as your spirit.',
  'Wishing you the happiest birthday, beautiful Gurleen.',
];

export const TREE_WISHES = [
  'May your smile never fade.',
  'Wishing you endless adventures.',
  'May your heart always be full.',
  'You deserve all the stars.',
  'May joy follow you always.',
  'Wishing you sweet surprises.',
  'May your dreams take flight.',
  'You are loved beyond words.',
  'May peace surround you.',
  'Wishing you golden moments.',
  'May your path be bright.',
  'You light up the world.',
  'May happiness be your companion.',
  'Wishing you magical days.',
  'May love fill your heart.',
  'You are truly special.',
  'May your year be wonderful.',
  'Wishing you beautiful memories.',
  'May your spirit soar.',
  'You are a blessing.',
  'May today sparkle for you.',
  'Wishing you warm embraces.',
  'May your wishes come true.',
  'You make life beautiful.',
  'May serenity find you.',
  'Wishing you blooming happiness.',
  'May your laughter echo.',
  'You are pure magic.',
  'May kindness return to you.',
  'Wishing you starlit nights.',
  'May your heart dance.',
  'You are extraordinary.',
  'May beauty surround you.',
  'Wishing you sweet serenity.',
  'May your dreams blossom.',
  'You are a rare gem.',
  'May joy be endless.',
  'Wishing you moonbeam kisses.',
  'May your soul shine.',
  'You are absolutely amazing.',
  'May love guide your way.',
  'Wishing you fairy tale moments.',
  'May your birthday glow.',
  'You are the sunshine.',
  'May wonder never leave you.',
  'Wishing you rose petal dreams.',
  'May your heart sing.',
  'You are a star.',
  'May today be perfect.',
  'Wishing you the happiest birthday, Gurleen.',
];

export const LANTERN_MESSAGES = [
  'You make every day brighter.',
  'Your smile is my favorite sight.',
  'May your dreams always come true.',
  'You are loved more than you know.',
  'The world is better with you in it.',
  'May happiness always find you.',
  'You are a beautiful soul.',
  'Wishing you endless joy.',
  'Your kindness inspires everyone.',
  'May your heart always be light.',
  'You deserve all the love.',
  'May stars guide your path.',
  'You are truly one of a kind.',
  'May your year be magical.',
  'You light up my world.',
  'May peace fill your days.',
  'You are absolutely wonderful.',
  'May your wishes float to the sky.',
  'You are a gift to this world.',
  'May love surround you always.',
];

export const LETTER_CONTENT = `My Dearest Gurleen,

On this beautiful day, I want you to know how incredibly special you are. Your smile has the power to brighten even the darkest days, and your kindness touches everyone around you in ways you may never fully realize.

You are a rare and beautiful soul — someone who brings warmth, joy, and magic wherever you go. Your laughter is like music, your heart is pure gold, and your spirit shines brighter than a thousand stars.

Today, we celebrate not just your birthday, but the wonderful person you are. May this year bring you endless happiness, beautiful adventures, and dreams that come true.

Never stop being the amazing person you are. The world is infinitely better because you exist in it.

With all my heart,
Someone who admires you deeply ❤️`;

export const MEMORY_BOOK_PAGES = [
  {
    id: 1,
    caption: 'A Beautiful Beginning',
    memory:
      'Every great story starts with someone special — and that someone is you, Gurleen.',
    illustration: '🌸',
    photoColor: '#E8A0BF',
  },
  {
    id: 2,
    caption: 'Moments of Joy',
    memory:
      'The way you laugh can turn an ordinary moment into something magical.',
    illustration: '✨',
    photoColor: '#C8B6E2',
  },
  {
    id: 3,
    caption: 'Your Beautiful Smile',
    memory:
      'Your smile is like sunshine breaking through the clouds — warm, radiant, and unforgettable.',
    illustration: '😊',
    photoColor: '#F7E7CE',
  },
  {
    id: 4,
    caption: 'Kindness Personified',
    memory:
      'Your heart is so full of kindness that it spills over and touches everyone around you.',
    illustration: '💝',
    photoColor: '#FFDAB9',
  },
  {
    id: 5,
    caption: 'Dreams & Stars',
    memory:
      'You dream with your eyes open, and the stars seem to shine brighter when you look at them.',
    illustration: '⭐',
    photoColor: '#D4BBFC',
  },
  {
    id: 6,
    caption: 'A Chapter Unwritten',
    memory:
      'The best chapters of your story are still being written — and they will be extraordinary.',
    illustration: '📖',
    photoColor: '#B76E79',
  },
];

export const MEMORY_BOOK_COVER = {
  title: 'Memories of',
  name: 'Gurleen',
  subtitle: 'A story written in moments of magic',
};

function galleryAvatar(seed, backgroundColor) {
  const bg = backgroundColor.replace('#', '');
  return `https://api.dicebear.com/7.x/lorelei/png?seed=${encodeURIComponent(seed)}&backgroundColor=${bg}&size=512`;
}

export const GALLERY_PHOTOS = [
  {
    id: 1,
    caption: 'Golden Moments',
    date: 'A day to remember',
    color: '#E8A0BF',
    illustration: '🌅',
    rotate: -5,
    src: galleryAvatar('gurleen-golden', '#E8A0BF'),
  },
  {
    id: 2,
    caption: 'Sweet Memories',
    date: 'Forever in my heart',
    color: '#C8B6E2',
    illustration: '🍰',
    rotate: 3,
    src: galleryAvatar('gurleen-sweet', '#C8B6E2'),
  },
  {
    id: 3,
    caption: 'Beautiful Days',
    date: 'Sunshine & smiles',
    color: '#F7E7CE',
    illustration: '🌸',
    rotate: -2,
    src: galleryAvatar('gurleen-beautiful', '#F7E7CE'),
  },
  {
    id: 4,
    caption: 'Pure Joy',
    date: 'Laughter everywhere',
    color: '#FFDAB9',
    illustration: '🎈',
    rotate: 4,
    src: galleryAvatar('gurleen-joy', '#FFDAB9'),
  },
  {
    id: 5,
    caption: 'Lovely Times',
    date: 'Moments of magic',
    color: '#D4BBFC',
    illustration: '✨',
    rotate: -4,
    src: galleryAvatar('gurleen-lovely', '#D4BBFC'),
  },
  {
    id: 6,
    caption: 'Magic Moments',
    date: 'Unforgettable',
    color: '#B76E79',
    illustration: '💫',
    rotate: 2,
    src: galleryAvatar('gurleen-magic', '#B76E79'),
  },
  {
    id: 7,
    caption: 'Cherished',
    date: 'Close to my heart',
    color: '#E8A0BF',
    illustration: '💝',
    rotate: -3,
    src: galleryAvatar('gurleen-cherished', '#E8A0BF'),
  },
  {
    id: 8,
    caption: 'Precious',
    date: 'A treasure of time',
    color: '#C8B6E2',
    illustration: '🌙',
    rotate: 5,
    src: galleryAvatar('gurleen-precious', '#C8B6E2'),
  },
];

export const LETTER_META = {
  greeting: 'A Letter For You',
  subtitle: 'Sealed with love',
  sealInitial: 'G',
  signature: 'Someone who admires you deeply',
  openHint: 'Tap the wax seal to open',
};

export const BIRTHDAY_WISHES_META = {
  featuredHint: 'A wish blooms for you...',
  tapHint: 'Tap a petal to read a wish',
  totalLabel: 'wishes gathered for you',
};

export const WISH_BUBBLE_POSITIONS = [
  { left: '4%', top: '12%', size: 'sm', delay: 0, duration: 5.2 },
  { left: '18%', top: '8%', size: 'md', delay: 0.6, duration: 6 },
  { left: '72%', top: '10%', size: 'sm', delay: 1.2, duration: 5.5 },
  { left: '88%', top: '18%', size: 'md', delay: 0.3, duration: 6.4 },
  { left: '2%', top: '38%', size: 'md', delay: 1.8, duration: 5.8 },
  { left: '14%', top: '52%', size: 'sm', delay: 0.9, duration: 6.2 },
  { left: '78%', top: '42%', size: 'sm', delay: 2.1, duration: 5.4 },
  { left: '92%', top: '55%', size: 'md', delay: 1.5, duration: 6.6 },
  { left: '6%', top: '72%', size: 'sm', delay: 0.4, duration: 5.6 },
  { left: '22%', top: '82%', size: 'md', delay: 2.4, duration: 6.1 },
  { left: '68%', top: '78%', size: 'sm', delay: 1.1, duration: 5.9 },
  { left: '86%', top: '72%', size: 'md', delay: 0.7, duration: 6.3 },
  { left: '32%', top: '6%', size: 'sm', delay: 1.6, duration: 5.3 },
  { left: '58%', top: '4%', size: 'sm', delay: 2.0, duration: 6.5 },
  { left: '38%', top: '88%', size: 'sm', delay: 0.2, duration: 5.7 },
  { left: '52%', top: '90%', size: 'md', delay: 1.4, duration: 6.0 },
];

export const FALLING_PETALS = [
  { left: '8%', delay: 0, duration: 12, size: 14 },
  { left: '22%', delay: 2, duration: 14, size: 10 },
  { left: '35%', delay: 4, duration: 11, size: 12 },
  { left: '48%', delay: 1, duration: 13, size: 16 },
  { left: '62%', delay: 3, duration: 15, size: 11 },
  { left: '75%', delay: 5, duration: 12, size: 13 },
  { left: '88%', delay: 2.5, duration: 14, size: 9 },
  { left: '15%', delay: 6, duration: 13, size: 12 },
  { left: '42%', delay: 3.5, duration: 11, size: 15 },
  { left: '68%', delay: 1.5, duration: 16, size: 10 },
  { left: '92%', delay: 4.5, duration: 12, size: 14 },
  { left: '28%', delay: 7, duration: 14, size: 11 },
];

export const WISH_TREE_META = {
  tapHint: 'Tap a glowing leaf to receive a wish',
  revealedLabel: 'A wish for you',
  pickedLabel: 'leaves touched with magic',
};

export const TREE_LEAF_POSITIONS = [
  { x: 200, y: 72, rotate: 0, scale: 1.1, wishIndex: 0 },
  { x: 158, y: 88, rotate: -25, scale: 0.95, wishIndex: 2 },
  { x: 242, y: 88, rotate: 25, scale: 0.95, wishIndex: 4 },
  { x: 128, y: 108, rotate: -35, scale: 0.9, wishIndex: 6 },
  { x: 272, y: 108, rotate: 35, scale: 0.9, wishIndex: 8 },
  { x: 200, y: 118, rotate: 5, scale: 1.05, wishIndex: 10 },
  { x: 168, y: 138, rotate: -20, scale: 1, wishIndex: 12 },
  { x: 232, y: 138, rotate: 20, scale: 1, wishIndex: 14 },
  { x: 112, y: 148, rotate: -40, scale: 0.85, wishIndex: 16 },
  { x: 288, y: 148, rotate: 40, scale: 0.85, wishIndex: 18 },
  { x: 145, y: 168, rotate: -15, scale: 0.95, wishIndex: 20 },
  { x: 255, y: 168, rotate: 15, scale: 0.95, wishIndex: 22 },
  { x: 200, y: 178, rotate: 0, scale: 1.1, wishIndex: 24 },
  { x: 178, y: 198, rotate: -22, scale: 0.9, wishIndex: 26 },
  { x: 222, y: 198, rotate: 22, scale: 0.9, wishIndex: 28 },
  { x: 108, y: 188, rotate: -45, scale: 0.8, wishIndex: 30 },
  { x: 292, y: 188, rotate: 45, scale: 0.8, wishIndex: 32 },
  { x: 138, y: 212, rotate: -18, scale: 0.95, wishIndex: 34 },
  { x: 262, y: 212, rotate: 18, scale: 0.95, wishIndex: 36 },
  { x: 200, y: 222, rotate: 8, scale: 1, wishIndex: 38 },
  { x: 165, y: 238, rotate: -28, scale: 0.85, wishIndex: 40 },
  { x: 235, y: 238, rotate: 28, scale: 0.85, wishIndex: 42 },
  { x: 92, y: 228, rotate: -50, scale: 0.75, wishIndex: 44 },
  { x: 308, y: 228, rotate: 50, scale: 0.75, wishIndex: 46 },
  { x: 200, y: 252, rotate: 0, scale: 0.9, wishIndex: 48 },
];
